# Generated by Django 5.1.2 on 2024-10-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0004_eventdata_end_date_eventdata_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(blank=True, choices=[('approve', 'Approve'), ('deny', 'Deny')], max_length=10),
        ),
    ]
