# Generated by Django 5.1.2 on 2024-10-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0005_comment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='comment_videos/'),
        ),
    ]
