# Generated by Django 5.1.2 on 2024-10-28 00:32

import EMS.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0006_comment_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdata',
            name='status',
        ),
        migrations.AddField(
            model_name='eventdata',
            name='sitting_plan',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='sitting_plan_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='comment_videos/', validators=[EMS.models.validate_video_file]),
        ),
    ]
