# Generated by Django 5.1.2 on 2024-10-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0007_remove_eventdata_status_eventdata_sitting_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='heart_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
