# Generated by Django 5.1.2 on 2024-10-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0008_comment_heart_count_comment_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.TextField(default='user'),
            preserve_default=False,
        ),
    ]
