# Generated by Django 5.1.2 on 2024-11-01 09:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0012_alter_eventdata_geast_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdata',
            name='schedule_plan',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='schedule_plan_images/'),
            preserve_default=False,
        ),
    ]
