# Generated by Django 5.1.2 on 2024-11-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0016_alter_eventdata_category_alter_eventdata_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
