# Generated by Django 5.1.2 on 2024-11-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0017_alter_eventdata_end_date_alter_eventdata_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='image',
            field=models.ImageField(upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
