# Generated by Django 5.1.2 on 2024-11-02 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0019_alter_eventdata_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='EMS.eventdata'),
        ),
    ]
