# Generated by Django 5.1.2 on 2024-11-03 04:55

import EMS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0020_alter_image_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='schedule_plan',
            field=models.FileField(blank=True, upload_to='schedule_plan_files/', validators=[EMS.models.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='sitting_plan',
            field=models.FileField(blank=True, upload_to='sitting_plan_files/', validators=[EMS.models.validate_pdf]),
        ),
    ]
