# Generated by Django 5.1.2 on 2024-11-08 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0021_alter_eventdata_schedule_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='schedule_plan',
            field=models.ImageField(blank=True, upload_to='schedule_plan_files/'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='sitting_plan',
            field=models.ImageField(blank=True, upload_to='sitting_plan_files/'),
        ),
        migrations.CreateModel(
            name='ScheduleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sitting_plan_files/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_plans', to='EMS.eventdata')),
            ],
        ),
        migrations.CreateModel(
            name='SeatingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sitting_plan_files/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitting_plans', to='EMS.eventdata')),
            ],
        ),
    ]
