# Generated by Django 5.1.3 on 2024-11-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0022_alter_eventdata_schedule_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdata',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
