# Generated by Django 5.1.3 on 2024-11-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0025_eventdetail_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
