# Generated by Django 5.1.3 on 2024-11-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0029_eventdata_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdata',
            name='saving_mode',
            field=models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish')], default='other', max_length=20),
        ),
    ]
