# Generated by Django 5.1.3 on 2024-11-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0030_eventdata_saving_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='saving_mode',
            field=models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish')], default='draft', max_length=20),
        ),
    ]
