# Generated by Django 5.1.3 on 2024-11-24 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0031_alter_eventdata_saving_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='additional_info',
        ),
    ]
