# Generated by Django 5.1.3 on 2024-11-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0034_scheduleimage_name_seatingimage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleimage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='seatingimage',
            name='name',
        ),
        migrations.AddField(
            model_name='eventdata',
            name='schedule_plan_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='eventdata',
            name='sitting_plan_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
