# Generated by Django 5.1.3 on 2024-11-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0037_alter_eventdata_schedule_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='schedule_plan',
            field=models.ImageField(blank=True, default='Schedule Plan', upload_to='schedule_plan_files/'),
        ),
    ]
