# Generated by Django 5.1.3 on 2024-12-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0038_alter_eventdata_schedule_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='guest',
            name='confirm',
            field=models.CharField(blank=True, choices=[('confirm', 'Confirm'), ('not_confirm', 'Not Confirm')], default='confirm', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='category',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('public', 'Public')], default='public', max_length=10),
        ),
    ]
